import { IProduct } from '../models/Product';

export const COMPREHENSIVE_PUZZOLANA_CATALOG = [
  // ==========================================
  // 1. CRUSHERS - JAW CRUSHERS (PJC SERIES)
  // ==========================================
  {
    productId: 'PJC-9060',
    name: 'Primary Single-Toggle Jaw Crusher PJC 9060',
    slug: 'pjc-9060',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Jaw Crushers',
    productFamily: 'PJC Heavy Duty Series',
    modelNumber: 'PJC 9060',
    shortDescription: 'High-reduction primary jaw crusher designed for medium aggregate quarries and mining extraction.',
    fullDescription: 'The Puzzolana PJC 9060 provides rugged cast steel housing, forged alloy steel eccentric shaft, and spherical roller bearings engineered for abrasive granite, basalt, and limestone crushing.',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 120,
    capacityMaxTPH: 250,
    maxFeedSizeMM: 500,
    powerRatingKW: 75,
    dischargeSizeMM: '75 - 150 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Aggregates & Quarrying', 'Highway & Road Construction', 'Cement & Concrete Batching'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'River Gravel / Cobbles'],
    features: [
      'Forged alloy steel eccentric shaft with spherical roller bearings',
      'Hydraulic gap setting shim adjustment',
      'Reversible high-manganese jaw plates for extended life',
      'Deep symmetrical crushing chamber profile',
    ],
    benefits: [
      'High reduction ratio of up to 6:1',
      'Low kilowatt-hour power consumption per ton',
      'Ease of maintenance with modular wear components',
    ],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Feed Opening (Width x Depth)', value: '900 x 600', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '500', unit: 'mm' },
          { name: 'Discharge Setting Range (CSS)', value: '75 - 150', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity' as const,
        specifications: [
          { name: 'Minimum Rated Capacity', value: '120', unit: 'TPH' },
          { name: 'Maximum Rated Capacity', value: '250', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [
          { name: 'Electric Motor Rating', value: '75', unit: 'kW (100 HP)' },
          { name: 'Flywheel Operating Speed', value: '280', unit: 'RPM' },
        ],
      },
      {
        groupName: 'Dimensions' as const,
        specifications: [
          { name: 'Total Machine Weight', value: '18,500', unit: 'kg' },
          { name: 'Overall Dimensions (L x W x H)', value: '2950 x 2100 x 2400', unit: 'mm' },
        ],
      },
    ],
    brochureUrl: '/downloads/pjc-series-brochure.pdf',
    datasheetUrl: '/downloads/pjc-9060-datasheet.pdf',
    relatedProductSlugs: ['pjc-11075', 'pcc-1500', 'pgf-1140'],
    status: 'published' as const,
    viewsCount: 184,
  },
  {
    productId: 'PJC-11075',
    name: 'Primary Single-Toggle Jaw Crusher PJC 11075',
    slug: 'pjc-11075',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Jaw Crushers',
    productFamily: 'PJC Heavy Duty Series',
    modelNumber: 'PJC 11075',
    shortDescription: 'Workhorse primary jaw crusher for commercial aggregate producers handling 200–400 TPH plant configurations.',
    fullDescription: 'PJC 11075 is engineered for heavy quarry primary reduction with an 1100x750mm feed opening and massive counterweighted flywheels.',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 200,
    capacityMaxTPH: 400,
    maxFeedSizeMM: 650,
    powerRatingKW: 110,
    dischargeSizeMM: '90 - 200 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Aggregates & Quarrying', 'Mining & Mineral Processing', 'Highway & Road Construction'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Iron Ore', 'Quartzite'],
    features: [
      'Stress-relieved cast steel frame',
      'Heavy-duty alloy forged eccentric shaft',
      'Dual toggle-plate mechanical safety mechanism',
    ],
    benefits: ['Superior throughput reliability in abrasive rock', 'Extended bearing longevity'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Feed Opening (Width x Depth)', value: '1100 x 750', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '650', unit: 'mm' },
          { name: 'Discharge Setting Range (CSS)', value: '90 - 200', unit: 'mm' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Electric Motor Rating', value: '110', unit: 'kW (150 HP)' }],
      },
      {
        groupName: 'Dimensions' as const,
        specifications: [{ name: 'Total Weight', value: '28,000', unit: 'kg' }],
      },
    ],
    relatedProductSlugs: ['pjc-14076', 'pcc-2000'],
    status: 'published' as const,
    viewsCount: 312,
  },
  {
    productId: 'PJC-14076',
    name: 'Primary Heavy Duty Jaw Crusher PJC 14076',
    slug: 'pjc-14076',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Jaw Crushers',
    productFamily: 'PJC Heavy Duty Series',
    modelNumber: 'PJC 14076',
    shortDescription: 'Flagship primary jaw crusher for high-capacity 350–600 TPH hard-rock aggregate plants and mining operations.',
    fullDescription: 'The PJC 14076 delivers unmatched primary crushing throughput with a 1400x760mm feed throat and rugged one-piece cast steel pitman.',
    primaryImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 350,
    capacityMaxTPH: 600,
    maxFeedSizeMM: 850,
    powerRatingKW: 160,
    dischargeSizeMM: '100 - 250 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Aggregates & Quarrying', 'Mining & Mineral Processing', 'Infrastructure Conglomerates'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Iron Ore', 'Quartzite', 'Bauxite'],
    features: [
      'Forged alloy steel eccentric shaft with 4 large spherical roller bearings',
      'Hydraulic wedge setting adjustment system',
      'Heavy ribbed cast steel pitman',
    ],
    benefits: ['Maximum tons per hour throughput', 'Handles boulders up to 850mm'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Feed Opening', value: '1400 x 760', unit: 'mm' },
          { name: 'Max Feed Size', value: '850', unit: 'mm' },
          { name: 'CSS Discharge Range', value: '100 - 250', unit: 'mm' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Drive Motor', value: '160', unit: 'kW (215 HP)' }],
      },
      {
        groupName: 'Dimensions' as const,
        specifications: [{ name: 'Total Weight', value: '42,500', unit: 'kg' }],
      },
    ],
    relatedProductSlugs: ['pjc-16012', 'pcc-3000'],
    status: 'published' as const,
    viewsCount: 540,
  },

  // ==========================================
  // 2. CRUSHERS - CONE CRUSHERS (PCC SERIES)
  // ==========================================
  {
    productId: 'PCC-2000',
    name: 'Multi-Cylinder Hydraulic Cone Crusher PCC 2000',
    slug: 'pcc-2000',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Cone Crushers',
    productFamily: 'PCC Hydraulic Series',
    modelNumber: 'PCC 2000',
    shortDescription: 'High-performance multi-cylinder hydraulic cone crusher for secondary and tertiary aggregate shaping and reduction.',
    fullDescription: 'The PCC 2000 features automated hydraulic setting control, continuous tramp iron clearance, and optimized crushing chamber geometries delivering high cubical yield.',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 180,
    capacityMaxTPH: 350,
    maxFeedSizeMM: 215,
    powerRatingKW: 160,
    dischargeSizeMM: '12 - 38 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Aggregates & Quarrying', 'Railway Ballast Production', 'Highway & Road Construction'],
    materialsHandled: ['Basalt / Trap Rock', 'Granite', 'River Gravel / Cobbles'],
    features: [
      'Multi-cylinder hydraulic tramp clearing & adjustment',
      'Advanced PLC-based control with automatic calibration',
      'Interchangeable standard and short-head crushing cavities',
    ],
    benefits: ['Superior cubical product shape', 'High reduction ratio', 'Safe automated tramp clearing'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Cone Head Diameter', value: '1200', unit: 'mm' },
          { name: 'Max Feed Size', value: '215', unit: 'mm' },
          { name: 'CSS Discharge Setting', value: '12 - 38', unit: 'mm' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Drive Motor', value: '160', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pjc-14076', 'pvi-1200'],
    status: 'published' as const,
    viewsCount: 310,
  },
  {
    productId: 'PCC-3000',
    name: 'Heavy Duty Hydraulic Cone Crusher PCC 3000',
    slug: 'pcc-3000',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Cone Crushers',
    productFamily: 'PCC Hydraulic Series',
    modelNumber: 'PCC 3000',
    shortDescription: 'High-tonnage cone crusher for 300–550 TPH secondary and tertiary hard-rock crushing applications.',
    fullDescription: 'Engineered for high-tonnage aggregate and mining circuits requiring maximum reduction and continuous hydraulic protection.',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 280,
    capacityMaxTPH: 550,
    maxFeedSizeMM: 260,
    powerRatingKW: 250,
    dischargeSizeMM: '16 - 45 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Mining & Mineral Processing', 'Aggregates & Quarrying'],
    materialsHandled: ['Granite', 'Iron Ore', 'Quartzite', 'Basalt'],
    features: ['High-throw eccentric geometry', 'Hydraulic motor setting rotation', 'Heavy cast steel mainframe'],
    benefits: ['High circulating load handling', 'Consistent output gradation'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Cone Head Diameter', value: '1400', unit: 'mm' },
          { name: 'Max Feed Size', value: '260', unit: 'mm' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Motor Power', value: '250', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pjc-14076', 'pcc-2000'],
    status: 'published' as const,
    viewsCount: 220,
  },

  // ==========================================
  // 3. CRUSHERS - VSI IMPACTORS (PVI SERIES)
  // ==========================================
  {
    productId: 'PVI-1200',
    name: 'Vertical Shaft Impactor PVI 1200',
    slug: 'pvi-1200',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'VSI Impactors',
    productFamily: 'PVI Shaping Series',
    modelNumber: 'PVI 1200',
    shortDescription: 'Tertiary and quaternary rock-on-rock vertical shaft impactor for manufactured sand and cubical aggregate shaping.',
    fullDescription: 'The Puzzolana PVI 1200 uses rock-on-rock autogenous crushing principles to produce IS 383 Zone II plaster and concrete sand with low wear cost.',
    primaryImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 180,
    capacityMaxTPH: 320,
    maxFeedSizeMM: 45,
    powerRatingKW: 220,
    dischargeSizeMM: '0 - 5 mm, 5 - 10 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Manufactured Sand Production', 'Concrete Aggregate Shaping', 'Glass & Slag Recycling'],
    materialsHandled: ['Granite', 'Basalt', 'River Gravel', 'Quartzite'],
    features: ['High-speed dynamically balanced rotor', 'Dual drive motor arrangement', 'Rock-shelf autogenous lining'],
    benefits: ['Flakiness index reduction to <10%', 'High manufactured sand yield', 'Low wear metal replacement cost'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Rotor Diameter', value: '950', unit: 'mm' },
          { name: 'Max Feed Size', value: '45', unit: 'mm' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Twin Drive Motors', value: '2 x 110 (220 total)', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pcc-2000', 'pbw-1000'],
    status: 'published' as const,
    viewsCount: 295,
  },

  // ==========================================
  // 4. FEEDERS & SCREENS (PGF & PVS SERIES)
  // ==========================================
  {
    productId: 'PGF-1345',
    name: 'Heavy Duty Grizzly Feeder PGF 1345',
    slug: 'pgf-1345',
    category: 'feeders-and-screens',
    categoryName: 'Feeders & Screens',
    subcategory: 'Grizzly Feeders',
    productFamily: 'PGF Series',
    modelNumber: 'PGF 1345',
    shortDescription: 'Heavy-duty vibratory grizzly feeder designed to withstand dump truck shock loading and scalp natural fines before primary crushing.',
    fullDescription: 'Features stepped grizzly bars and dual unbalance exciter shafts mounted on heavy coil springs.',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 300,
    capacityMaxTPH: 600,
    maxFeedSizeMM: 850,
    powerRatingKW: 30,
    dischargeSizeMM: 'Scalped <100mm',
    mobilityType: 'Stationary' as const,
    applications: ['Primary Crushing Feed', 'Dump Hopper Feed', 'Mining Extraction'],
    materialsHandled: ['Granite', 'Basalt', 'Iron Ore', 'Limestone'],
    features: ['Stepped tapered grizzly section', 'Heavy HARDOX liner plates', 'Dual counter-rotating vibrator pods'],
    benefits: ['Bypasses natural fines, increasing jaw crusher capacity by up to 25%'],
    specifications: [
      {
        groupName: 'Dimensions' as const,
        specifications: [{ name: 'Trough Size (Width x Length)', value: '1300 x 4500', unit: 'mm' }],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Vibrator Drive Motor', value: '30', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pjc-14076', 'pvs-1860'],
    status: 'published' as const,
    viewsCount: 160,
  },
  {
    productId: 'PVS-1860-4D',
    name: '4-Deck Circular Motion Vibrating Screen PVS 1860',
    slug: 'pvs-1860-4d',
    category: 'feeders-and-screens',
    categoryName: 'Feeders & Screens',
    subcategory: 'Vibrating Screens',
    productFamily: 'PVS Sizing Series',
    modelNumber: 'PVS 1860-4D',
    shortDescription: 'High-throughput 4-deck inclined circular motion vibrating screen for multi-fraction aggregate separation.',
    fullDescription: 'The PVS 1860-4D delivers simultaneous production of 0-5mm sand, 10mm, 20mm, and 40mm aggregate fractions with high screening efficiency.',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 250,
    capacityMaxTPH: 500,
    maxFeedSizeMM: 100,
    powerRatingKW: 30,
    dischargeSizeMM: '4 Fractions: 0-5, 10, 20, 40 mm',
    mobilityType: 'Stationary' as const,
    applications: ['Commercial Aggregate Sizing', 'Mining Classification', 'Railway Ballast Screening'],
    materialsHandled: ['Granite', 'Basalt', 'River Gravel', 'Limestone'],
    features: ['Huck-bolted side plates (no welding)', 'Modular polyurethane / wire mesh deck options', 'Oil lubricated spherical bearings'],
    benefits: ['High screening efficiency (>92%)', 'Zero structural fatigue cracking'],
    specifications: [
      {
        groupName: 'Dimensions' as const,
        specifications: [
          { name: 'Deck Size (Width x Length)', value: '1800 x 6000', unit: 'mm' },
          { name: 'Number of Decks', value: '4', unit: 'Decks' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Drive Motor', value: '30', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pcc-2000', 'pvi-1200'],
    status: 'published' as const,
    viewsCount: 275,
  },

  // ==========================================
  // 5. CLASSIFIERS & SAND WASHING (PBW & PSW)
  // ==========================================
  {
    productId: 'PSW-200',
    name: 'Hydro-Cyclone Sand Washing Plant PSW 200',
    slug: 'psw-200',
    category: 'classifiers',
    categoryName: 'Classifiers & Washing',
    subcategory: 'Hydro-Cyclone Plants',
    productFamily: 'PSW Sand Series',
    modelNumber: 'PSW 200',
    shortDescription: 'Complete hydro-cyclone sand washing and dewatering plant producing silt-free manufactured sand.',
    fullDescription: 'Equipped with polyurethane-lined cyclones, rubber-lined slurry pumps, and high-frequency dewatering screen for maximum fine sand recovery and <12% discharge moisture.',
    primaryImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 150,
    capacityMaxTPH: 250,
    maxFeedSizeMM: 8,
    powerRatingKW: 75,
    dischargeSizeMM: '0 - 4 mm Silt-Free Sand',
    mobilityType: 'Stationary' as const,
    applications: ['M-Sand Plaster & Concrete Production', 'Silica Sand Washing', 'River Sand Recovery'],
    materialsHandled: ['Crushed Granite Sand', 'River Sand', 'Silica Sand'],
    features: ['Polyurethane hydro-cyclone cluster', 'High-frequency linear dewatering screen', 'Heavy rubber lined slurry pump'],
    benefits: ['Removes -75 micron silt below 3%', 'Dewatered sand stackable immediately on conveyor'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Washing Capacity', value: '150 - 250', unit: 'TPH' },
          { name: 'Product Moisture Level', value: '< 12%', unit: '%' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Slurry Pump + Screen Power', value: '75', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pvi-1200', 'pvs-1860-4d'],
    status: 'published' as const,
    viewsCount: 340,
  },

  // ==========================================
  // 6. MOBILE CRUSHERS (TRACK MOUNTED)
  // ==========================================
  {
    productId: 'PTJ-11075',
    name: 'Track Mobile Jaw Crusher PTJ 11075',
    slug: 'ptj-11075',
    category: 'mobile-crushers',
    categoryName: 'Mobile Crushers',
    subcategory: 'Track Jaw',
    productFamily: 'PTJ Mobile Series',
    modelNumber: 'PTJ 11075',
    shortDescription: 'High-mobility track-mounted primary jaw crushing plant with onboard diesel generator and hydraulic drive.',
    fullDescription: 'Rapid deployment for quarry face relocation, road infrastructure contracts, and on-site C&D waste crushing.',
    primaryImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 200,
    capacityMaxTPH: 400,
    maxFeedSizeMM: 650,
    powerRatingKW: 240,
    dischargeSizeMM: '75 - 175 mm',
    mobilityType: 'Track-Mounted' as const,
    applications: ['Highway & Road Construction', 'C&D Waste Recycling', 'Aggregates & Quarrying'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'C&D Concrete Waste'],
    features: [
      'Heavy-duty crawler track undercarriage',
      'Onboard overband magnetic separator for rebar removal',
      'Radio remote control for tramming and feeder operation',
    ],
    benefits: ['Fast site setup (< 30 mins)', 'Eliminates raw rock haulage cost', 'Dual-power electric plug-in option'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Crusher Feed Opening', value: '1100 x 750', unit: 'mm' },
          { name: 'Mobility Chassis', value: 'Heavy Duty Crawler Tracks' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Diesel Engine Rating', value: '240', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['ptc-2000', 'pts-1860'],
    status: 'published' as const,
    viewsCount: 420,
  },
  {
    productId: 'PTC-2000',
    name: 'Track Mobile Cone Crusher PTC 2000',
    slug: 'ptc-2000',
    category: 'mobile-crushers',
    categoryName: 'Mobile Crushers',
    subcategory: 'Track Cone',
    productFamily: 'PTC Mobile Series',
    modelNumber: 'PTC 2000',
    shortDescription: 'Track-mounted multi-cylinder cone crusher with onboard prescreen and metal detector.',
    fullDescription: 'Pairs seamlessly with PTJ mobile jaw for complete high-throughput mobile aggregate trains.',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 180,
    capacityMaxTPH: 350,
    maxFeedSizeMM: 215,
    powerRatingKW: 280,
    dischargeSizeMM: '12 - 38 mm',
    mobilityType: 'Track-Mounted' as const,
    applications: ['Highway & Road Construction', 'Commercial Aggregate Production'],
    materialsHandled: ['Granite', 'Basalt', 'River Gravel'],
    features: ['Automated metal detection & bypass chute', 'Onboard diesel generator'],
    benefits: ['High mobility in multi-stage contracts'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [{ name: 'Cone Diameter', value: '1200', unit: 'mm' }],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Engine Power', value: '280', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['ptj-11075', 'pts-1860'],
    status: 'published' as const,
    viewsCount: 260,
  },

  // ==========================================
  // 7. MINING SOLUTIONS (PFB SERIES)
  // ==========================================
  {
    productId: 'PFB-1500',
    name: 'Heavy Duty Feeder Breaker PFB 1500',
    slug: 'pfb-1500',
    category: 'mining',
    categoryName: 'Mining Solutions',
    subcategory: 'Feeder Breakers',
    productFamily: 'PFB Mining Series',
    modelNumber: 'PFB 1500',
    shortDescription: 'Heavy-duty continuous mineral feeder breaker for open-cast coal, lignite, and soft mineral reduction up to 2000 TPH.',
    fullDescription: 'Combines a massive armored flight chain conveyor with a high-torque rotary pick roll breaker to crush run-of-mine lumps directly at the mining face.',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 1000,
    capacityMaxTPH: 2000,
    maxFeedSizeMM: 1200,
    powerRatingKW: 350,
    dischargeSizeMM: '< 200 mm',
    mobilityType: 'Skid-Mounted' as const,
    applications: ['Coal Mining Extraction', 'Lignite Handling', 'Soft Mineral Primary Sizing'],
    materialsHandled: ['Coal / Lignite', 'Bauxite', 'Gypsum', 'Soft Limestone'],
    features: ['Armored twin outboard strand chain conveyor', 'Tungsten-carbide tipped breaker picks', 'Integrated hydraulic lump breaker roll'],
    benefits: ['Low profile allows direct haul truck dumping without civil ramps', 'High volumetric throughput'],
    specifications: [
      {
        groupName: 'Capacity' as const,
        specifications: [
          { name: 'Nominal Tonnage', value: '1000 - 2000', unit: 'TPH' },
          { name: 'Max Feed Lump', value: '1200', unit: 'mm' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Breaker + Conveyor Drive', value: '350', unit: 'kW' }],
      },
    ],
    relatedProductSlugs: ['pjc-16012', 'pgf-1550'],
    status: 'published' as const,
    viewsCount: 310,
  },

  // ==========================================
  // 8. ROAD BUILDING MACHINERY (PPR SERIES)
  // ==========================================
  {
    productId: 'PPR-9000',
    name: 'Hydrostatic Sensor Asphalt Paver PPR 9000',
    slug: 'ppr-9000',
    category: 'road-building',
    categoryName: 'Road Building Machinery',
    subcategory: 'Road Pavers',
    productFamily: 'PPR Paver Series',
    modelNumber: 'PPR 9000',
    shortDescription: 'Heavy-duty hydrostatic sensor paver with 9.0 meter paving width for National Highways and expressway projects.',
    fullDescription: 'Equipped with electronic slope and grade sensors, heavy tamping & vibrating screed with gas/electric heating for dense bituminous paving.',
    primaryImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 300,
    capacityMaxTPH: 600,
    maxFeedSizeMM: 40,
    powerRatingKW: 140,
    dischargeSizeMM: 'Paving Width: 2.5m – 9.0m',
    mobilityType: 'Wheel-Mounted' as const,
    applications: ['Expressway & Highway Construction', 'Airport Runway Paving', 'Heavy Industrial Pavements'],
    materialsHandled: ['Dense Bituminous Macadam (DBM)', 'Bituminous Concrete (BC)', 'Wet Mix Macadam (WMM)'],
    features: ['Electronic grade and slope control system', 'Hydraulically extendable high-compaction screed', 'Dual operator console with joystick controls'],
    benefits: ['Superior riding quality and IRI index compliance', 'High initial pre-compaction (>90%)'],
    specifications: [
      {
        groupName: 'General' as const,
        specifications: [
          { name: 'Basic Paving Width', value: '2.5', unit: 'm' },
          { name: 'Maximum Paving Width with Extensions', value: '9.0', unit: 'm' },
          { name: 'Max Laydown Capacity', value: '600', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power' as const,
        specifications: [{ name: 'Engine Power', value: '140', unit: 'kW (190 HP)' }],
      },
    ],
    relatedProductSlugs: ['pjc-11075', 'pcc-2000'],
    status: 'published' as const,
    viewsCount: 280,
  },
];
