export interface DownloadAsset {
  id: string;
  title: string;
  category: 'Product Brochures' | 'Technical Datasheets' | 'CAD Layouts & GA' | 'O&M Manuals' | 'Corporate & ISO Certs';
  equipmentCategory: 'All Machinery' | 'Jaw Crushers' | 'Cone Crushers' | 'VSI & Sand Washing' | 'Track Mobile Plants' | 'Screens & Feeders' | 'Corporate';
  productModel?: string;
  fileType: 'PDF' | 'DWG' | 'STEP' | 'ZIP';
  fileSize: string;
  downloadCount: number;
  isGated: boolean;
  description: string;
  lastUpdated: string;
}

export const VERIFIED_DOWNLOAD_ASSETS: DownloadAsset[] = [
  // 1. PRODUCT BROCHURES
  {
    id: 'DL-BROCH-MASTER-2026',
    title: 'Puzzolana Complete Heavy Machinery Fleet Catalogue (2026 Edition)',
    category: 'Product Brochures',
    equipmentCategory: 'All Machinery',
    fileType: 'PDF',
    fileSize: '14.8 MB',
    downloadCount: 3840,
    isGated: false,
    description: 'Comprehensive 48-page catalog covering stationary crushers, track mobile units, sand washing systems, surface miners, and asphalt pavers.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-BROCH-PJC-JAW',
    title: 'PJC Series Primary Jaw Crushers Technical Brochure',
    category: 'Product Brochures',
    equipmentCategory: 'Jaw Crushers',
    productModel: 'PJC 9060 to PJC 14076',
    fileType: 'PDF',
    fileSize: '4.2 MB',
    downloadCount: 2190,
    isGated: false,
    description: 'Deep-cavity jaw crushers, toggle geometry, cast-steel frame specifications, and hydraulic CSS adjustment mechanisms.',
    lastUpdated: 'February 2026',
  },
  {
    id: 'DL-BROCH-PCC-CONE',
    title: 'PCC Series Hydraulic Cone Crushers Brochure',
    category: 'Product Brochures',
    equipmentCategory: 'Cone Crushers',
    productModel: 'PCC 1100 to PCC 3000',
    fileType: 'PDF',
    fileSize: '5.1 MB',
    downloadCount: 1980,
    isGated: false,
    description: 'Hydroset hydraulic gap control, multi-chamber cavity profiles (Extra Coarse to Extra Fine), and tramp iron relief cylinders.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-BROCH-TRACK-FLEET',
    title: 'Track-Mounted Mobile Crushing & Screening Fleet Brochure',
    category: 'Product Brochures',
    equipmentCategory: 'Track Mobile Plants',
    productModel: 'PTJ / PTC / PTS Series',
    fileType: 'PDF',
    fileSize: '6.4 MB',
    downloadCount: 2640,
    isGated: false,
    description: 'Dual-power direct electric/diesel generators, hydrostatic track drives, and fast-track highway crushing configurations.',
    lastUpdated: 'February 2026',
  },
  {
    id: 'DL-BROCH-SAND-WASH',
    title: 'M-Sand Hydrocyclone Washing & VSI Shaping Systems Brochure',
    category: 'Product Brochures',
    equipmentCategory: 'VSI & Sand Washing',
    productModel: 'PSW 100/150 & PVI Series',
    fileType: 'PDF',
    fileSize: '4.8 MB',
    downloadCount: 1820,
    isGated: false,
    description: 'IS:383 Zone II concrete sand recovery, zero silt loss vortex finders, and closed-loop water clarification thickeners.',
    lastUpdated: 'January 2026',
  },

  // 2. TECHNICAL DATASHEETS
  {
    id: 'DL-DS-PJC-14076',
    title: 'PJC 14076 Heavy Mining Jaw Crusher Sizing & Specification Sheet',
    category: 'Technical Datasheets',
    equipmentCategory: 'Jaw Crushers',
    productModel: 'PJC 14076',
    fileType: 'PDF',
    fileSize: '1.8 MB',
    downloadCount: 1450,
    isGated: false,
    description: 'Detailed feed opening dimensions (1400 x 1070 mm), motor power (200 kW), CSS gap curve ratings (125mm to 250mm), and weight tables.',
    lastUpdated: 'February 2026',
  },
  {
    id: 'DL-DS-PCC-2000',
    title: 'PCC 2000 Secondary Hydraulic Cone Crusher Engineering Datasheet',
    category: 'Technical Datasheets',
    equipmentCategory: 'Cone Crushers',
    productModel: 'PCC 2000',
    fileType: 'PDF',
    fileSize: '2.1 MB',
    downloadCount: 1320,
    isGated: false,
    description: 'Cavity sizing charts, eccentric throw speeds, cooling oil flow requirements, and gradation distribution curves in granite & basalt.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-DS-PVI-100',
    title: 'PVI 100 Vertical Shaft Impactor (VSI) Operational Datasheet',
    category: 'Technical Datasheets',
    equipmentCategory: 'VSI & Sand Washing',
    productModel: 'PVI 100',
    fileType: 'PDF',
    fileSize: '1.6 MB',
    downloadCount: 980,
    isGated: false,
    description: 'Dual-stream cascade flow calculations, rotor peripheral speed limits (up to 75 m/s), and tungsten carbide wear tip specifications.',
    lastUpdated: 'February 2026',
  },
  {
    id: 'DL-DS-PVS-2060',
    title: 'PVS 2060 4-Deck Heavy Vibrating Sizing Screen Technical Datasheet',
    category: 'Technical Datasheets',
    equipmentCategory: 'Screens & Feeders',
    productModel: 'PVS 2060',
    fileType: 'PDF',
    fileSize: '1.4 MB',
    downloadCount: 860,
    isGated: false,
    description: 'Deck surface area (12 m² per deck), eccentric stroke amplitude, polyurethane modular fastening systems, and dynamic foundation loads.',
    lastUpdated: 'January 2026',
  },

  // 3. 2D / 3D CAD LAYOUTS & GA DRAWINGS (Gated B2B Assets)
  {
    id: 'DL-CAD-600TPH-GA',
    title: '600 TPH 4-Stage Stationary Granite Plant General Arrangement (GA) Drawing',
    category: 'CAD Layouts & GA',
    equipmentCategory: 'All Machinery',
    fileType: 'DWG',
    fileSize: '18.4 MB',
    downloadCount: 890,
    isGated: true,
    description: 'Comprehensive 2D/3D AutoCAD layout showing hopper heights, surge bunkers, conveyor slopes, crusher centerlines, and stockpile clearances.',
    lastUpdated: 'February 2026',
  },
  {
    id: 'DL-CAD-PTJ-FOOTPRINT',
    title: 'PTJ 11075 Track Jaw Crusher 3D Transport & Working Clearance Model',
    category: 'CAD Layouts & GA',
    equipmentCategory: 'Track Mobile Plants',
    productModel: 'PTJ 11075',
    fileType: 'STEP',
    fileSize: '24.2 MB',
    downloadCount: 670,
    isGated: true,
    description: '3D STEP solid model for site planning, excavator feed reach verification, and low-bed transport dimensions.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-CAD-PJC-LOADS',
    title: 'PJC 14076 Jaw Crusher Concrete Foundation Load & Anchor Bolt Plan',
    category: 'CAD Layouts & GA',
    equipmentCategory: 'Jaw Crushers',
    productModel: 'PJC 14076',
    fileType: 'PDF',
    fileSize: '3.2 MB',
    downloadCount: 940,
    isGated: true,
    description: 'Civil structural engineering guide with static and dynamic peak impact loads for RCC crusher pier design.',
    lastUpdated: 'February 2026',
  },

  // 4. OPERATION & MAINTENANCE (O&M) MANUALS (Gated B2B Assets)
  {
    id: 'DL-OM-JAW-LINERS',
    title: 'Jaw Crusher Manganese Liner Replacement & Bolt Torque Manual',
    category: 'O&M Manuals',
    equipmentCategory: 'Jaw Crushers',
    fileType: 'PDF',
    fileSize: '4.5 MB',
    downloadCount: 1120,
    isGated: true,
    description: 'Step-by-step procedures for cheek plate renewal, reversible jaw plate rotation, wedge tightening torque specs, and backing compound pouring.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-OM-CONE-HYD',
    title: 'PCC Hydraulic Cone Hydroset System Calibration & Lube Manual',
    category: 'O&M Manuals',
    equipmentCategory: 'Cone Crushers',
    fileType: 'PDF',
    fileSize: '5.8 MB',
    downloadCount: 970,
    isGated: true,
    description: 'Hydraulic pressure settings, accumulator pre-charge protocols, bronze bushing clearance checks, and ISO VG 150 oil filtration guidelines.',
    lastUpdated: 'February 2026',
  },

  // 5. CORPORATE & ISO CERTIFICATIONS
  {
    id: 'DL-CERT-ISO-9001',
    title: 'ISO 9001:2015 Quality Management System Certificate',
    category: 'Corporate & ISO Certs',
    equipmentCategory: 'Corporate',
    fileType: 'PDF',
    fileSize: '850 KB',
    downloadCount: 1540,
    isGated: false,
    description: 'Accredited certification for design, heavy manufacturing, induction casting foundries, and plant commissioning.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-CERT-ISO-14001',
    title: 'ISO 14001:2015 Environmental Management System Certificate',
    category: 'Corporate & ISO Certs',
    equipmentCategory: 'Corporate',
    fileType: 'PDF',
    fileSize: '820 KB',
    downloadCount: 1210,
    isGated: false,
    description: 'Certified environmental governance across Pashamylaram and Cherlapally manufacturing complexes.',
    lastUpdated: 'January 2026',
  },
  {
    id: 'DL-CERT-ISO-45001',
    title: 'ISO 45001:2018 Occupational Health & Safety Management Certificate',
    category: 'Corporate & ISO Certs',
    equipmentCategory: 'Corporate',
    fileType: 'PDF',
    fileSize: '890 KB',
    downloadCount: 1180,
    isGated: false,
    description: 'Certified safety systems, foundry hazard controls, and zero-accident occupational governance.',
    lastUpdated: 'January 2026',
  },
];
