import { MachineryProduct, EquipmentCategorySlug } from '../types';

export interface CategoryMetadata {
  id: EquipmentCategorySlug;
  name: string;
  tagline: string;
  description: string;
  heroImage: string;
  subcategories: string[];
  keyStrengths: string[];
  totalModels: number;
}

export const OFFICIAL_CATEGORIES: CategoryMetadata[] = [
  {
    id: 'crushers',
    name: 'Crushers',
    tagline: 'High-Reduction Primary, Secondary & Tertiary Crushing Solutions',
    description: 'Heavy-duty Single Toggle Jaw Crushers, Hydraulic Cone Crushers, and Vertical Shaft Impactors (VSI) engineered for extreme rock compressive strength, maximum cubical shape, and minimal operational downtime.',
    heroImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Jaw Crushers', 'Cone Crushers', 'VSI Crushers', 'Impact Crushers'],
    keyStrengths: ['Up to 1200 TPH Capacity', 'Forged Alloy Steel Eccentric Shafts', 'Automated Hydraulic Tramp Release', 'Superior Flakiness & Elongation Index'],
    totalModels: 5,
  },
  {
    id: 'feeders-and-screens',
    name: 'Feeders & Screens',
    tagline: 'Precision Sizing & High-Throughput Controlled Feeding',
    description: 'Vibrating Grizzly Feeders with step bars and Inclined Circular Motion Vibrating Screens designed with modular poly/wire mesh decks for accurate separation of scalped aggregates and fine minerals.',
    heroImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Grizzly Feeders', 'Circular Motion Screens', 'Horizontal Screens', 'Pan Feeders'],
    keyStrengths: ['Variable Speed Drives', 'Heavy-Duty Coil & Rubber Spring Isolation', 'Stress-Relieved Side Plates with Huck Bolts', 'Up to 4-Deck Configurations'],
    totalModels: 2,
  },
  {
    id: 'classifiers',
    name: 'Sand Washing & Classifiers',
    tagline: 'High-Purity M-Sand Production & Fines Recovery Systems',
    description: 'Bucket Wheel Sand Classifiers and Hydrocyclone Ultra-Fine Recovery Plants ensuring silt/clay removal below 3% to meet stringent IS 383 Zone II concrete sand specifications.',
    heroImage: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Bucket Wheel Classifiers', 'Hydrocyclone Sand Washers', 'Dewatering Screens'],
    keyStrengths: ['< 3% Silt Content Compliance', 'Zero Silt Loss Technology', 'Polyurethane Liners & High-Wear Hydrocyclones', 'Low Moisture Discharge'],
    totalModels: 2,
  },
  {
    id: 'mobile-crushers',
    name: 'Mobile Track Plants',
    tagline: 'Self-Propelled Track-Mounted Crushing & Screening Plants',
    description: 'Heavy-duty diesel-hydraulic and dual-power track-mounted crushing units designed for rapid quarry mobilization, highway contracting, and on-site concrete demolition processing.',
    heroImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Track Jaw Plants', 'Track Cone Plants', 'Track Screening Plants', 'Track Impact Plants'],
    keyStrengths: ['Wireless Remote Drive Control', 'Dual Power (Grid / Onboard Diesel-Gen)', 'Hydraulic Fold Conveyors for Fast Transport', 'Integrated Dust Suppression'],
    totalModels: 2,
  },
  {
    id: 'semi-mobile',
    name: 'Semi-Mobile / Skid Plants',
    tagline: 'Modular Pre-Assembled Skid & Wheel-Mounted Configurations',
    description: 'Pre-wired and modularly skid-mounted two-stage and three-stage crushing plants engineered to minimize civil foundation costs and enable swift plant relocations.',
    heroImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Wheel-Mounted Crushers', 'Skid-Mounted Two-Stage Plants', 'Modular Three-Stage Plants'],
    keyStrengths: ['Zero Concrete Foundation Requirement', 'Quick-Plug Electrical Control Cabinets', 'Heavy I-Beam Skid Structures', 'Fast 48-Hour Site Commissioning'],
    totalModels: 1,
  },
  {
    id: 'mining',
    name: 'Surface Miners & Mining',
    tagline: 'Continuous Blast-Free Open-Cast Mining & Sizers',
    description: 'Heavy-duty Continuous Surface Miners eliminating blasting hazards, secondary crushing, and reducing environmental impact for limestone, bauxite, and coal open-pit operations.',
    heroImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Surface Miners', 'Mineral Sizers', 'Heavy Open-Cast Feeders'],
    keyStrengths: ['Continuous Cutting & Loading', 'Zero Explosives / No Blast Vibration', 'Selective Thin-Seam Extraction', 'High Purity Raw Material Feed'],
    totalModels: 2,
  },
  {
    id: 'waste-processing',
    name: 'Feeder Breakers & Waste',
    tagline: 'Underground/Surface Breakers & Heavy C&D Waste Recovery',
    description: 'Heavy drag-chain flight feeder breakers and C&D waste recyclers capable of crushing run-of-mine lumpy coal, shale, limestone, and reinforced concrete debris without stalling.',
    heroImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Feeder Breakers', 'C&D Waste Plants', 'Slag Recovery Systems'],
    keyStrengths: ['High-Torque Pick Rollers', 'Direct Truck Dump Low-Profile Hopper', 'Rebar & Tramp Iron Tolerance', 'Wear-Resistant Hardox Liners'],
    totalModels: 1,
  },
  {
    id: 'road-building',
    name: 'Road Pavers & Infrastructure',
    tagline: 'Precision Hydrostatic Sensor Pavers for Highway Construction',
    description: 'Heavy-duty hydrostatic asphalt and wet-mix macadam sensor pavers featuring hydraulic extendable screeds, electronic grade & slope sensors, and dual-side material augers.',
    heroImage: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=1600&q=80',
    subcategories: ['Hydrostatic Sensor Pavers', 'Asphalt Pavers', 'Soil Compactors'],
    keyStrengths: ['Electronic Dual Grade & Slope Sensing', 'Hydraulic Extendable Screed up to 9.0m', 'High-Density Dual Tamper Screed', 'Cummins / Kirloskar Fuel-Efficient Engine'],
    totalModels: 1,
  },
];

export const VERIFIED_FRONTEND_PRODUCTS: MachineryProduct[] = [
  {
    id: 'PJC-9060',
    name: 'Primary Single-Toggle Jaw Crusher PJC 9060',
    slug: 'pjc-9060',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Jaw Crushers',
    productFamily: 'PJC Heavy Duty Series',
    modelNumber: 'PJC 9060',
    shortDescription: 'High-reduction primary jaw crusher designed for medium aggregate quarries and mining extraction.',
    fullDescription: 'The Puzzolana PJC 9060 provides rugged cast steel housing, forged alloy steel eccentric shaft, and spherical roller bearings engineered for abrasive granite, basalt, and limestone crushing.',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    ],
    capacityMinTPH: 120,
    capacityMaxTPH: 250,
    maxFeedSizeMM: 500,
    powerRatingKW: 75,
    dischargeSizeMM: '75 - 150 mm',
    mobilityType: 'Stationary',
    applications: ['Aggregates & Quarrying', 'Highway & Road Construction', 'Cement & Concrete Batching'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'River Gravel / Cobbles'],
    features: [
      'Forged alloy steel eccentric shaft with spherical roller bearings',
      'Hydraulic gap setting shim adjustment',
      'Reversible high-manganese jaw plates for extended life',
      'Deep symmetrical crushing chamber profile',
    ],
    benefits: [
      'High reduction ratio of up to 6:1',
      'Low kilowatt-hour power consumption per ton',
      'Ease of maintenance with modular wear components',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Feed Opening (Width x Depth)', value: '900 x 600', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '500', unit: 'mm' },
          { name: 'Discharge Setting Range (CSS)', value: '75 - 150', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Minimum Rated Capacity', value: '120', unit: 'TPH' },
          { name: 'Maximum Rated Capacity', value: '250', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Electric Motor Rating', value: '75', unit: 'kW (100 HP)' },
          { name: 'Flywheel Operating Speed', value: '280', unit: 'RPM' },
        ],
      },
      {
        groupName: 'Dimensions',
        specifications: [
          { name: 'Total Machine Weight', value: '18,500', unit: 'kg' },
          { name: 'Overall Dimensions (L x W x H)', value: '2950 x 2100 x 2400', unit: 'mm' },
        ],
      },
    ],
    brochureUrl: '/downloads/pjc-series-brochure.pdf',
    datasheetUrl: '/downloads/pjc-9060-datasheet.pdf',
    relatedProductSlugs: ['pjc-11075', 'pcc-1500', 'pgf-1140'],
    status: 'published',
  },
  {
    id: 'PJC-11075',
    name: 'Primary Single-Toggle Jaw Crusher PJC 11075',
    slug: 'pjc-11075',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Jaw Crushers',
    productFamily: 'PJC Heavy Duty Series',
    modelNumber: 'PJC 11075',
    shortDescription: 'Workhorse primary jaw crusher for commercial aggregate producers handling 200–400 TPH plant configurations.',
    fullDescription: 'PJC 11075 is engineered for heavy quarry primary reduction with an 1100x750mm feed opening and massive counterweighted flywheels for smooth continuous torque.',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 200,
    capacityMaxTPH: 400,
    maxFeedSizeMM: 650,
    powerRatingKW: 110,
    dischargeSizeMM: '90 - 200 mm',
    mobilityType: 'Stationary',
    applications: ['Aggregates & Quarrying', 'Mining & Mineral Processing', 'Highway & Road Construction'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Iron Ore', 'Quartzite'],
    features: [
      'Stress-relieved cast steel frame',
      'Heavy-duty alloy forged eccentric shaft',
      'Dual toggle-plate mechanical safety mechanism',
    ],
    benefits: [
      'Engineered for 24/7 continuous quarry cycles',
      'Higher throughput at lower specific energy consumption',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Feed Opening', value: '1100 x 750', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '650', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Capacity Range', value: '200 - 400', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Electric Motor Rating', value: '110', unit: 'kW (150 HP)' },
        ],
      },
    ],
    brochureUrl: '/downloads/pjc-series-brochure.pdf',
    relatedProductSlugs: ['pjc-14076', 'pcc-2000', 'pvs-2060'],
    status: 'published',
  },
  {
    id: 'PJC-14076',
    name: 'Heavy Mining Primary Jaw Crusher PJC 14076',
    slug: 'pjc-14076',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Jaw Crushers',
    productFamily: 'PJC Heavy Duty Series',
    modelNumber: 'PJC 14076',
    shortDescription: 'Flagship high-capacity primary jaw crusher for large infrastructure quarries and open-pit mining operations.',
    fullDescription: 'The flagship PJC 14076 handles massive boulders up to 900mm with an enormous feed opening of 1400x1100mm, delivering up to 750 TPH primary output.',
    primaryImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 350,
    capacityMaxTPH: 750,
    maxFeedSizeMM: 900,
    powerRatingKW: 160,
    dischargeSizeMM: '125 - 250 mm',
    mobilityType: 'Stationary',
    applications: ['Mining & Mineral Processing', 'Aggregates & Quarrying', 'Highway & Road Construction'],
    materialsHandled: ['Granite', 'Iron Ore', 'Basalt / Trap Rock', 'Limestone', 'Bauxite'],
    features: [
      'Massive 1400 x 1100 mm jaw chamber',
      'Reinforced box-section fabricated main frame',
      'Hydraulic wedge CSS setting system',
    ],
    benefits: [
      'Eliminates secondary blasting requirements for large pit boulders',
      'Extreme durability in abrasive iron ore and hard trap rock',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Feed Opening', value: '1400 x 1100', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '900', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Capacity Range', value: '350 - 750', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Electric Motor Rating', value: '160', unit: 'kW (215 HP)' },
        ],
      },
    ],
    brochureUrl: '/downloads/pjc-series-brochure.pdf',
    relatedProductSlugs: ['pcc-2500', 'pgf-1550', 'ptj-11075'],
    status: 'published',
  },
  {
    id: 'PCC-2000',
    name: 'Hydraulic Cone Crusher PCC 2000',
    slug: 'pcc-2000',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'Cone Crushers',
    productFamily: 'PCC Hydro-Cone Series',
    modelNumber: 'PCC 2000',
    shortDescription: 'High-reduction secondary and tertiary cone crusher engineered for precise aggregate shape and high cubicity.',
    fullDescription: 'Puzzolana PCC 2000 cone crushers incorporate advanced hydraulic tramp relief, automated mantle positioning, and inter-particle crushing for superior shape consistency.',
    primaryImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 150,
    capacityMaxTPH: 350,
    maxFeedSizeMM: 220,
    powerRatingKW: 160,
    dischargeSizeMM: '12 - 38 mm',
    mobilityType: 'Stationary',
    applications: ['Aggregates & Quarrying', 'Highway & Road Construction', 'Railway Ballast Production'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'Quartzite'],
    features: [
      'Hydraulic overload protection with automatic reset',
      'Touchscreen PLC control panel with real-time CSS monitoring',
      'High-speed eccentric throw for high inter-particle crushing',
    ],
    benefits: [
      'Optimizes aggregate flakiness index < 15%',
      'Unmatched reduction ratios in secondary/tertiary stages',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Cone Diameter', value: '1200', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '220', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Capacity Range', value: '150 - 350', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Motor Rating', value: '160', unit: 'kW (215 HP)' },
        ],
      },
    ],
    brochureUrl: '/downloads/pcc-cone-brochure.pdf',
    relatedProductSlugs: ['pjc-11075', 'pvi-100', 'pvs-2060'],
    status: 'published',
  },
  {
    id: 'PVI-100',
    name: 'Vertical Shaft Impactor PVI 100',
    slug: 'pvi-100',
    category: 'crushers',
    categoryName: 'Crushers',
    subcategory: 'VSI Crushers',
    productFamily: 'PVI Sand Maker Series',
    modelNumber: 'PVI 100',
    shortDescription: 'Rock-on-Rock & Rock-on-Anvil tertiary VSI crusher for superior cubical aggregates and high-quality manufactured sand (M-Sand).',
    fullDescription: 'The Puzzolana PVI 100 operates on rock-on-rock crushing principles to achieve optimal shape, cubicity, and precise gradation of sand.',
    primaryImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 80,
    capacityMaxTPH: 220,
    maxFeedSizeMM: 45,
    powerRatingKW: 185,
    dischargeSizeMM: '0 - 5 mm (M-Sand) / 10 - 20 mm',
    mobilityType: 'Stationary',
    applications: ['Highway & Road Construction', 'Cement & Concrete Batching', 'Aggregates & Quarrying'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'River Gravel / Cobbles'],
    features: [
      'High-speed balanced rotor with tungsten carbide tips',
      'Dual motor drive system for uniform torque transmission',
      'Rock-shelf anvil chamber minimizing liner wear',
    ],
    benefits: [
      'Produces premium IS 383 Zone II compliant manufactured sand',
      'Superior cubical aggregate shape for high-strength concrete',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Rotor Diameter', value: '850', unit: 'mm' },
          { name: 'Maximum Feed Size', value: '45', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Capacity Range', value: '80 - 220', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Drive Motor Rating', value: '185', unit: 'kW (250 HP Dual Drive)' },
        ],
      },
    ],
    brochureUrl: '/downloads/pvi-vsi-brochure.pdf',
    relatedProductSlugs: ['pcc-2000', 'psw-150', 'pvs-2060'],
    status: 'published',
  },
  {
    id: 'PGF-1140',
    name: 'Heavy Duty Grizzly Feeder PGF 1140',
    slug: 'pgf-1140',
    category: 'feeders-and-screens',
    categoryName: 'Feeders & Screens',
    subcategory: 'Grizzly Feeders',
    productFamily: 'PGF Vibrating Feeder Series',
    modelNumber: 'PGF 1140',
    shortDescription: 'Rugged primary grizzly feeder with step bars for scalping quarry run fines before primary jaw crushing.',
    fullDescription: 'Puzzolana PGF 1140 feeders ensure uniform regulated feed to primary crushers while scalping out undersized natural dirt and clay.',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 200,
    capacityMaxTPH: 450,
    maxFeedSizeMM: 700,
    powerRatingKW: 18.5,
    dischargeSizeMM: 'Regulated Grizzly By-Pass',
    mobilityType: 'Stationary',
    applications: ['Aggregates & Quarrying', 'Mining & Mineral Processing', 'Highway & Road Construction'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'Iron Ore'],
    features: [
      'Twin eccentric vibrating mechanism',
      'Cast manganese stepped grizzly bars',
      'Hardox liner plates on pan floor',
    ],
    benefits: [
      'Prevents crusher blinding and enhances jaw throughput by up to 25%',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Tray Dimensions (W x L)', value: '1100 x 4000', unit: 'mm' },
          { name: 'Grizzly Section Length', value: '1500', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Feeding Capacity', value: '200 - 450', unit: 'TPH' },
        ],
      },
    ],
    brochureUrl: '/downloads/feeders-screens-brochure.pdf',
    relatedProductSlugs: ['pjc-11075', 'pjc-9060'],
    status: 'published',
  },
  {
    id: 'PVS-2060',
    name: 'Multi-Deck Vibrating Screen PVS 2060',
    slug: 'pvs-2060',
    category: 'feeders-and-screens',
    categoryName: 'Feeders & Screens',
    subcategory: 'Circular Motion Screens',
    productFamily: 'PVS High Capacity Screen Series',
    modelNumber: 'PVS 2060 (4-Deck)',
    shortDescription: 'High-frequency circular motion 4-deck vibrating screen for precise 4-product aggregate classification.',
    fullDescription: 'Engineered with huck-bolted side plates and heavy-duty eccentric vibrator shaft, the PVS 2060 provides accurate fractioning into 20mm, 10mm, 6mm, and M-Sand fractions.',
    primaryImage: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 180,
    capacityMaxTPH: 350,
    maxFeedSizeMM: 100,
    powerRatingKW: 22,
    dischargeSizeMM: '4 Fractions: 0-4mm, 4-10mm, 10-20mm, 20-40mm',
    mobilityType: 'Stationary',
    applications: ['Aggregates & Quarrying', 'Highway & Road Construction', 'Railway Ballast Production'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'River Gravel / Cobbles'],
    features: [
      'Circular throw vibration with adjustable amplitude',
      'Huck-bolted cross beams for zero weld stress',
      'Multi-deck modular polyurethane or wire-cloth screen mesh',
    ],
    benefits: [
      'High screening efficiency with non-blinding deck configurations',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Deck Size (W x L)', value: '2000 x 6000', unit: 'mm (6.5 x 20 ft)' },
          { name: 'Number of Decks', value: '4 Decks', unit: 'Decks' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Screening Capacity', value: '180 - 350', unit: 'TPH' },
        ],
      },
    ],
    brochureUrl: '/downloads/feeders-screens-brochure.pdf',
    relatedProductSlugs: ['pcc-2000', 'pvi-100', 'psw-150'],
    status: 'published',
  },
  {
    id: 'PSW-150',
    name: 'Hydrocyclone Sand Washing Plant PSW 150',
    slug: 'psw-150',
    category: 'classifiers',
    categoryName: 'Sand Washing & Classifiers',
    subcategory: 'Hydrocyclone Sand Washers',
    productFamily: 'PSW Sand Recovery Series',
    modelNumber: 'PSW 150',
    shortDescription: 'Advanced hydrocyclone and dewatering screen sand washing plant for silt removal < 3% and ultra-fine sand retention.',
    fullDescription: 'The PSW 150 delivers ultra-clean plaster sand and concrete sand conforming to IS 383 Zone II standards, equipped with a high-durability slurry pump, polyurethane hydrocyclones, and high G-force dewatering screen.',
    primaryImage: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 100,
    capacityMaxTPH: 160,
    maxFeedSizeMM: 5,
    powerRatingKW: 55,
    dischargeSizeMM: '0 - 2.5 mm / 0 - 4.75 mm Clean Sand',
    mobilityType: 'Skid-Mounted',
    applications: ['Cement & Concrete Batching', 'Highway & Road Construction', 'Aggregates & Quarrying'],
    materialsHandled: ['Granite M-Sand', 'River Sand / Silica', 'Limestone Fines'],
    features: [
      'Molded polyurethane hydrocyclone clusters',
      'High G-force linear motion dewatering screen (moisture < 12%)',
      'Rubber-lined heavy slurry sump pump',
    ],
    benefits: [
      'Reduces clay and silt content to under 3%',
      'Eliminates 75-micron fine sand loss into settling ponds',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Slurry Capacity', value: '350', unit: 'm³/hr' },
          { name: 'Output Sand Moisture', value: '< 12', unit: '%' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Clean Sand Output', value: '100 - 160', unit: 'TPH' },
        ],
      },
    ],
    brochureUrl: '/downloads/psw-sand-washing.pdf',
    relatedProductSlugs: ['pvi-100', 'pvs-2060'],
    status: 'published',
  },
  {
    id: 'PBW-120',
    name: 'Bucket Wheel Sand Classifier PBW 120',
    slug: 'pbw-120',
    category: 'classifiers',
    categoryName: 'Sand Washing & Classifiers',
    subcategory: 'Bucket Wheel Classifiers',
    productFamily: 'PBW Classifier Series',
    modelNumber: 'PBW 120',
    shortDescription: 'Heavy-duty bucket wheel classifier for natural river sand and quarry manufactured sand dewatering and desilting.',
    fullDescription: 'The PBW 120 utilizes dual heavy-gauge perforated bucket wheels and settling overflow weirs to wash, classify, and drain sand fractions.',
    primaryImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 80,
    capacityMaxTPH: 130,
    maxFeedSizeMM: 6,
    powerRatingKW: 11,
    dischargeSizeMM: '0 - 4.75 mm Dewatered Sand',
    mobilityType: 'Stationary',
    applications: ['Cement & Concrete Batching', 'Aggregates & Quarrying'],
    materialsHandled: ['River Sand / Silica', 'Granite M-Sand'],
    features: [
      'Dual bucket wheels with replaceable wear-resistant mesh',
      'Variable speed planetary gearbox drive',
    ],
    benefits: [
      'Low energy consumption per ton of washed product',
    ],
    specifications: [
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Processing Capacity', value: '80 - 130', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Drive Motor', value: '11', unit: 'kW (15 HP)' },
        ],
      },
    ],
    brochureUrl: '/downloads/pbw-classifier.pdf',
    relatedProductSlugs: ['psw-150', 'pvi-100'],
    status: 'published',
  },
  {
    id: 'PTJ-11075',
    name: 'Mobile Track Jaw Crusher PTJ 11075',
    slug: 'ptj-11075',
    category: 'mobile-crushers',
    categoryName: 'Mobile Track Plants',
    subcategory: 'Track Jaw Plants',
    productFamily: 'PTJ Mobile Series',
    modelNumber: 'PTJ 11075',
    shortDescription: 'Self-propelled track-mounted primary jaw crushing plant with integrated feeder, grizzly, and hydraulic folding conveyors.',
    fullDescription: 'Engineered for rapid mobilization and heavy quarry primary crushing, the PTJ 11075 combines high-capacity jaw crushing with direct dual-power diesel-electric flexibility.',
    primaryImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 200,
    capacityMaxTPH: 420,
    maxFeedSizeMM: 650,
    powerRatingKW: 260,
    dischargeSizeMM: '75 - 175 mm',
    mobilityType: 'Track-Mounted',
    applications: ['Highway & Road Construction', 'Mining & Mineral Processing', 'C&D Waste Recycling'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone', 'C&D Concrete Waste'],
    features: [
      'Heavy-duty crawler tracks with 2-speed travel and wireless remote control',
      'Fuel-efficient Tier 3 / Tier 4 compliant diesel engine with dual electric plug-in',
      'Hydraulic folding side and discharge conveyors for rapid 30-min setup',
    ],
    benefits: [
      'Eliminates in-pit haulage truck trips by crushing directly at the blast face',
      'Rapid site-to-site relocation with standard low-bed trailer transport',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Crusher Feed Opening', value: '1100 x 750', unit: 'mm' },
          { name: 'Travel Speed', value: '1.2', unit: 'km/h' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Capacity Range', value: '200 - 420', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Engine Power Output', value: '260', unit: 'kW (350 HP Diesel)' },
        ],
      },
    ],
    brochureUrl: '/downloads/ptj-mobile-crusher.pdf',
    relatedProductSlugs: ['ptc-2000', 'pjc-11075'],
    status: 'published',
  },
  {
    id: 'PTC-2000',
    name: 'Mobile Track Cone Crusher PTC 2000',
    slug: 'ptc-2000',
    category: 'mobile-crushers',
    categoryName: 'Mobile Track Plants',
    subcategory: 'Track Cone Plants',
    productFamily: 'PTC Mobile Series',
    modelNumber: 'PTC 2000',
    shortDescription: 'Track-mounted secondary/tertiary cone crusher plant with onboard screen and recirculating conveyor.',
    fullDescription: 'The PTC 2000 pairs hydraulic cone crushing technology with high-mobility tracked chassis, perfect for closed-circuit aggregate and ballast production on highway job sites.',
    primaryImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 150,
    capacityMaxTPH: 300,
    maxFeedSizeMM: 200,
    powerRatingKW: 280,
    dischargeSizeMM: '10 - 32 mm',
    mobilityType: 'Track-Mounted',
    applications: ['Highway & Road Construction', 'Railway Ballast Production', 'Aggregates & Quarrying'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone'],
    features: [
      'Hydraulic cone with tramp iron safety relief',
      'Onboard closed-circuit single-deck sizing screen',
    ],
    benefits: [
      'Produces finished spec aggregate in a single self-contained mobile train',
    ],
    specifications: [
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Capacity Range', value: '150 - 300', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Diesel Engine Rating', value: '280', unit: 'kW (375 HP)' },
        ],
      },
    ],
    brochureUrl: '/downloads/ptc-mobile-cone.pdf',
    relatedProductSlugs: ['ptj-11075', 'pcc-2000'],
    status: 'published',
  },
  {
    id: 'PSM-2200',
    name: 'Continuous Surface Miner PSM 2200',
    slug: 'psm-2200',
    category: 'mining',
    categoryName: 'Surface Miners & Mining',
    subcategory: 'Surface Miners',
    productFamily: 'PSM Surface Miner Series',
    modelNumber: 'PSM 2200',
    shortDescription: 'Continuous open-pit surface mining machine eliminating blasting for limestone, bauxite, and coal extraction.',
    fullDescription: 'Puzzolana PSM 2200 cuts, sizes, and loads mineral deposits in a single blast-free continuous pass, delivering tight gradation and high pit safety.',
    primaryImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 350,
    capacityMaxTPH: 650,
    maxFeedSizeMM: 100,
    powerRatingKW: 560,
    dischargeSizeMM: '0 - 50 mm Sized Direct Load',
    mobilityType: 'Track-Mounted',
    applications: ['Mining & Mineral Processing', 'Cement & Concrete Batching'],
    materialsHandled: ['Limestone', 'Bauxite', 'Coal / Lignite', 'Shale'],
    features: [
      '2.2-meter mechanically driven high-torque cutting drum',
      'Precision electronic laser-guided grade control',
      'Heavy-duty slewing high-capacity discharge conveyor',
    ],
    benefits: [
      'Eliminates drilling, blasting, and primary crusher stages entirely',
      'Enables selective thin-seam mining without polluting waste rock',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Cutting Drum Width', value: '2200', unit: 'mm' },
          { name: 'Maximum Cutting Depth', value: '300', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Mining Output', value: '350 - 650', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Heavy Diesel Engine', value: '560', unit: 'kW (750 HP Turbocharged)' },
        ],
      },
    ],
    brochureUrl: '/downloads/psm-surface-miner.pdf',
    relatedProductSlugs: ['pfb-1200', 'pjc-14076'],
    status: 'published',
  },
  {
    id: 'PFB-1200',
    name: 'Heavy Duty Feeder Breaker PFB 1200',
    slug: 'pfb-1200',
    category: 'waste-processing',
    categoryName: 'Feeder Breakers & Waste',
    subcategory: 'Feeder Breakers',
    productFamily: 'PFB Breaker Series',
    modelNumber: 'PFB 1200',
    shortDescription: 'Heavy-duty drag-chain flight feeder breaker for open-cast mines, dump stations, and lump sizing.',
    fullDescription: 'The PFB 1200 allows rear-dump quarry trucks to discharge directly into a low-profile receiving hopper, utilizing a rotary pick roll to size run-of-mine lumps onto downstream belts.',
    primaryImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 400,
    capacityMaxTPH: 1000,
    maxFeedSizeMM: 800,
    powerRatingKW: 220,
    dischargeSizeMM: '100 - 200 mm Sized',
    mobilityType: 'Skid-Mounted',
    applications: ['Mining & Mineral Processing', 'C&D Waste Recycling', 'Steel Slag Recovery'],
    materialsHandled: ['Coal / Lignite', 'Limestone', 'C&D Concrete Waste', 'Steel Slag'],
    features: [
      'High-tensile alloy forged flight chain with hardened manganese sprockets',
      'Tungsten carbide pick-toothed crushing roll',
      'Low-profile direct dump receiving hopper',
    ],
    benefits: [
      'Eliminates the requirement for deep concrete pits and civil ramps',
      'Handles heavy wet, sticky, and uncrushable tramp-contaminated feeds',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Hopper Volume', value: '25', unit: 'm³' },
          { name: 'Flight Chain Width', value: '1200', unit: 'mm' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Throughput Capacity', value: '400 - 1000', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Installed Power', value: '220', unit: 'kW (300 HP)' },
        ],
      },
    ],
    brochureUrl: '/downloads/pfb-feeder-breaker.pdf',
    relatedProductSlugs: ['psm-2200', 'pjc-14076'],
    status: 'published',
  },
  {
    id: 'PPR-900',
    name: 'Hydrostatic Sensor Paver PPR 900',
    slug: 'ppr-900',
    category: 'road-building',
    categoryName: 'Road Pavers & Infrastructure',
    subcategory: 'Hydrostatic Sensor Pavers',
    productFamily: 'PPR Highway Paver Series',
    modelNumber: 'PPR 900',
    shortDescription: 'High-precision hydrostatic sensor paver for asphalt, Bituminous Macadam (DBM), and Wet Mix Macadam (WMM) road paving.',
    fullDescription: 'Puzzolana PPR 900 delivers superior mat smoothness and compaction with hydraulic extendable screeds up to 9.0 meters, electronic dual grade/slope sensors, and high-capacity hopper.',
    primaryImage: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 250,
    capacityMaxTPH: 600,
    maxFeedSizeMM: 40,
    powerRatingKW: 125,
    dischargeSizeMM: 'Paving Width 2.5m - 9.0m',
    mobilityType: 'Wheel-Mounted',
    applications: ['Highway & Road Construction'],
    materialsHandled: ['Asphalt / Bituminous Macadam', 'Wet Mix Macadam (WMM)', 'Soil Stabilizers'],
    features: [
      'Hydraulically extendable screed with dual tamping and vibration',
      'Electronic MOBA / Sonic grade and slope sensors',
      'High capacity 14-ton receiving hopper with dual independent feed conveyors',
    ],
    benefits: [
      'Guarantees national highway smoothness compliance (IRI standards)',
      'High initial pre-compaction density above 90%',
    ],
    specifications: [
      {
        groupName: 'General',
        specifications: [
          { name: 'Basic Paving Width', value: '2.5', unit: 'm' },
          { name: 'Maximum Extended Width', value: '9.0', unit: 'm' },
          { name: 'Hopper Capacity', value: '14', unit: 'Tons' },
        ],
      },
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Paving Capacity', value: '250 - 600', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Engine Power', value: '125', unit: 'kW (170 HP Kirloskar/Cummins)' },
        ],
      },
    ],
    brochureUrl: '/downloads/ppr-paver-brochure.pdf',
    relatedProductSlugs: ['pjc-11075', 'pcc-2000'],
    status: 'published',
  },
  {
    id: 'PSM-SKID-200',
    name: 'Modular Skid-Mounted 2-Stage Plant PSM-SKID 200',
    slug: 'psm-skid-200',
    category: 'semi-mobile',
    categoryName: 'Semi-Mobile / Skid Plants',
    subcategory: 'Skid-Mounted Two-Stage Plants',
    productFamily: 'Modular Crushing Series',
    modelNumber: 'PSM-SKID 200',
    shortDescription: 'Pre-assembled, pre-wired two-stage crushing and screening plant on heavy steel skids with zero civil work requirements.',
    fullDescription: 'The PSM-SKID 200 integrates a PJC jaw crusher, PCC cone crusher, and PVS 4-deck screen on heavy I-beam skid modules for fast 48-hour quarry commissioning.',
    primaryImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
    galleryImages: [],
    capacityMinTPH: 150,
    capacityMaxTPH: 220,
    maxFeedSizeMM: 500,
    powerRatingKW: 295,
    dischargeSizeMM: '0-6mm, 10mm, 20mm, 40mm',
    mobilityType: 'Skid-Mounted',
    applications: ['Aggregates & Quarrying', 'Highway & Road Construction', 'Railway Ballast Production'],
    materialsHandled: ['Granite', 'Basalt / Trap Rock', 'Limestone'],
    features: [
      'Heavy structural steel skids requiring only compacted ground',
      'Centralized MCC electrical panel with interlocked sequence starters',
      'Inter-connecting heavy modular conveyors included',
    ],
    benefits: [
      'Cuts site establishment time from 4 months to 5 days',
      'Zero loss of civil foundation investments when moving quarries',
    ],
    specifications: [
      {
        groupName: 'Capacity',
        specifications: [
          { name: 'Plant Capacity', value: '150 - 220', unit: 'TPH' },
        ],
      },
      {
        groupName: 'Power',
        specifications: [
          { name: 'Total Connected Power', value: '295', unit: 'kW' },
        ],
      },
    ],
    brochureUrl: '/downloads/modular-skid-plants.pdf',
    relatedProductSlugs: ['pjc-9060', 'pcc-2000', 'pvs-2060'],
    status: 'published',
  },
];
