export interface DealerLocation {
  id: string;
  name: string;
  companyName: string;
  region: 'South India' | 'West India' | 'North India' | 'East India' | 'International / Global';
  city: string;
  state: string;
  country: string;
  address: string;
  phone: string;
  email: string;
  contactPerson: string;
  tier: 'Authorized 3S Dealership' | 'Regional Spares & Service Depot' | 'Corporate Regional Hub';
  authorizedLines: string[];
  capabilities: string[];
  operatingHours: string;
  sparesDepot: boolean;
  coordinates: {
    lat: number;
    lng: number;
  };
}

export interface DealerBenefit {
  title: string;
  description: string;
  icon: string;
  stat?: string;
}

export const PUZZOLANA_DEALERS: DealerLocation[] = [
  // SOUTH INDIA
  {
    id: 'PZD-HYD-HQ',
    name: 'Puzzolana Central Works & Distribution Depot',
    companyName: 'Puzzolana Machinery Fabricators (HQ)',
    region: 'South India',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    address: 'Puzzolana Towers, Road No. 2, Banjara Hills / Plant: IDA Pashamylaram, Hyderabad 500034',
    phone: '+91 (40) 2344 8800',
    email: 'dealers@puzzolana.com',
    contactPerson: 'Director - Channel Operations',
    tier: 'Corporate Regional Hub',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Sand Washing Systems', 'Surface Miners', 'Asphalt Pavers'],
    capabilities: ['24/7 Central Emergency Dispatch', 'Central Foundry Spares Stock (15,000+ Parts)', 'Technical Training Academy', 'Full Plant Overhauls'],
    operatingHours: 'Mon - Sat: 8:00 AM - 7:30 PM (24/7 Breakdown Cell)',
    sparesDepot: true,
    coordinates: { lat: 17.4126, lng: 78.4487 },
  },
  {
    id: 'PZD-BLR-01',
    name: 'Karnataka Heavy Equipment & Spares',
    companyName: 'Puzzolana South-West Channel Partner',
    region: 'South India',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    address: 'Plot 48, Peenya Industrial Area, Phase II, Bengaluru, Karnataka 560058',
    phone: '+91 (80) 4122 9300',
    email: 'bangalore.dealers@puzzolana.com',
    contactPerson: 'Regional Channel Manager',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Sand Washing Systems'],
    capabilities: ['Mobile Service Vans (3 Units)', 'Immediate Jaw & Cone Wear Liner Replacement', 'Electrical Panel Diagnostics'],
    operatingHours: 'Mon - Sat: 8:30 AM - 6:30 PM',
    sparesDepot: true,
    coordinates: { lat: 13.0285, lng: 77.5197 },
  },
  {
    id: 'PZD-CHN-01',
    name: 'Tamil Nadu Quarry Infrastructure Hub',
    companyName: 'Puzzolana Coastal Dealership Services',
    region: 'South India',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    address: 'Ambattur Industrial Estate, 3rd Main Road, Chennai, Tamil Nadu 600058',
    phone: '+91 (44) 2688 1200',
    email: 'chennai.support@puzzolana.com',
    contactPerson: 'Senior Service Engineer',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Sand Washing Systems', 'VSI Sand Makers'],
    capabilities: ['Hydrocyclone Re-lining', 'VSI Rotor Re-balancing', 'OEM Polyurethane Mesh Stock'],
    operatingHours: 'Mon - Sat: 9:00 AM - 6:00 PM',
    sparesDepot: true,
    coordinates: { lat: 13.0827, lng: 80.1600 },
  },
  {
    id: 'PZD-VJW-01',
    name: 'Andhra Aggregates Service Network',
    companyName: 'Puzzolana Amaravati Region Depot',
    region: 'South India',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    country: 'India',
    address: 'Autonagar Industrial Belt, Block 12, Vijayawada, Andhra Pradesh 520007',
    phone: '+91 (866) 254 7890',
    email: 'vijayawada.spares@puzzolana.com',
    contactPerson: 'Territory Service Lead',
    tier: 'Regional Spares & Service Depot',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units'],
    capabilities: ['Cone Hydraulic Oil Flushes', 'Laser Pulley Alignment', 'Manganese Cheek Plate Stock'],
    operatingHours: 'Mon - Sat: 8:30 AM - 6:30 PM',
    sparesDepot: true,
    coordinates: { lat: 16.5062, lng: 80.6480 },
  },

  // WEST INDIA
  {
    id: 'PZD-MUM-01',
    name: 'Western India Mineral & Infrastructure Hub',
    companyName: 'Puzzolana West Regional Command',
    region: 'West India',
    city: 'Mumbai / Navi Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'MIDC Industrial Area, Turbhe, Navi Mumbai, Maharashtra 400705',
    phone: '+91 (22) 2780 4455',
    email: 'mumbai.sales@puzzolana.com',
    contactPerson: 'Zonal Commercial Head',
    tier: 'Corporate Regional Hub',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Surface Miners', 'Asphalt Pavers'],
    capabilities: ['Infra Project Flowsheet Consultation', 'High-Tonnage Quarry Plant Audits', 'Immediate Dispatch Depot'],
    operatingHours: 'Mon - Sat: 9:00 AM - 7:00 PM',
    sparesDepot: true,
    coordinates: { lat: 19.0760, lng: 73.0076 },
  },
  {
    id: 'PZD-PUN-01',
    name: 'Maharashtra Heavy Crushing Dealership',
    companyName: 'Sahyadri Infra Machinery Partners',
    region: 'West India',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    address: 'Bhosari Industrial Estate, Sector 7, Pune, Maharashtra 411026',
    phone: '+91 (20) 2712 3344',
    email: 'pune.dealers@puzzolana.com',
    contactPerson: 'Channel Partner Principal',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Sand Washing Systems'],
    capabilities: ['24/7 Breakdown Field Support', 'PCC Cone Crusher Bushing Replacement', 'Tungsten Rotor Tip Stock'],
    operatingHours: 'Mon - Sat: 8:30 AM - 6:30 PM',
    sparesDepot: true,
    coordinates: { lat: 18.6298, lng: 73.8431 },
  },
  {
    id: 'PZD-AHM-01',
    name: 'Gujarat Mineral Processing Centre',
    companyName: 'Puzzolana Gujarat Regional Depot',
    region: 'West India',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    address: 'GIDC Industrial Estate, Vatva Phase IV, Ahmedabad, Gujarat 382445',
    phone: '+91 (79) 2583 6710',
    email: 'ahmedabad.spares@puzzolana.com',
    contactPerson: 'Regional Operations Manager',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Sand Washing Systems', 'Track Mobile Units'],
    capabilities: ['Silica Sand Plant Flowsheet Audits', 'Polyurethane Screen Optimization', 'Rapid Bearing Delivery'],
    operatingHours: 'Mon - Sat: 9:00 AM - 6:30 PM',
    sparesDepot: true,
    coordinates: { lat: 22.9567, lng: 72.6341 },
  },
  {
    id: 'PZD-RPR-01',
    name: 'Central Mining Equipment & Spares',
    companyName: 'Chhattisgarh Mining Machinery Corp',
    region: 'West India',
    city: 'Raipur',
    state: 'Chhattisgarh',
    country: 'India',
    address: 'Urla Industrial Complex, Ring Road No. 2, Raipur, Chhattisgarh 492003',
    phone: '+91 (771) 403 9100',
    email: 'raipur.dealers@puzzolana.com',
    contactPerson: 'Mining Division Lead',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Surface Miners', 'Feeder Breakers', 'Track Mobile Units'],
    capabilities: ['Iron Ore & Coal Crushing Overhauls', 'Heavy Manganese Jaw Liners Stock', 'On-Site Welder Dispatch'],
    operatingHours: 'Mon - Sat: 8:00 AM - 7:00 PM',
    sparesDepot: true,
    coordinates: { lat: 21.2828, lng: 81.6032 },
  },

  // NORTH INDIA
  {
    id: 'PZD-DEL-01',
    name: 'North India Zonal Command & Spares Depot',
    companyName: 'Puzzolana North Regional Headquarters',
    region: 'North India',
    city: 'New Delhi / NCR',
    state: 'Delhi NCR',
    country: 'India',
    address: 'Okhla Industrial Area, Phase III, New Delhi 110020',
    phone: '+91 (11) 4160 5500',
    email: 'delhi.zonal@puzzolana.com',
    contactPerson: 'Zonal Vice President',
    tier: 'Corporate Regional Hub',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Asphalt Pavers', 'Sand Washing Systems'],
    capabilities: ['National Highway Project Fleet Support', 'Fast-Track Warranty Processing', 'Express Spares Logistics'],
    operatingHours: 'Mon - Sat: 9:00 AM - 7:00 PM',
    sparesDepot: true,
    coordinates: { lat: 28.5355, lng: 77.2654 },
  },
  {
    id: 'PZD-JPR-01',
    name: 'Rajasthan Stone & Mining Machinery Hub',
    companyName: 'Marwar Infra Equipment & Spares',
    region: 'North India',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    address: 'VKIA Industrial Area, Road No. 9, Jaipur, Rajasthan 302013',
    phone: '+91 (141) 233 4890',
    email: 'jaipur.dealers@puzzolana.com',
    contactPerson: 'Territory Channel Head',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'VSI Sand Makers'],
    capabilities: ['Granite & Limestone Wear Parts Inventory', '24/7 Mobile Maintenance Unit', 'Rotor Balancing'],
    operatingHours: 'Mon - Sat: 8:30 AM - 6:30 PM',
    sparesDepot: true,
    coordinates: { lat: 26.9686, lng: 75.7663 },
  },
  {
    id: 'PZD-CHD-01',
    name: 'Punjab & Himachal Aggregate Plant Support',
    companyName: 'Northern Crushing Solutions',
    region: 'North India',
    city: 'Chandigarh / Mohali',
    state: 'Punjab',
    country: 'India',
    address: 'Industrial Area Phase 8B, Sector 74, Mohali, Punjab 160071',
    phone: '+91 (172) 509 2300',
    email: 'chandigarh.spares@puzzolana.com',
    contactPerson: 'Regional Service Incharge',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units'],
    capabilities: ['River Gravel (Round Stone) Crushing Diagnostics', 'Manganese Jaw Reversals', 'Emergency Spares'],
    operatingHours: 'Mon - Sat: 9:00 AM - 6:00 PM',
    sparesDepot: true,
    coordinates: { lat: 30.7046, lng: 76.7179 },
  },

  // EAST & CENTRAL INDIA
  {
    id: 'PZD-KOL-01',
    name: 'Eastern India Regional Headquarters & Depot',
    companyName: 'Puzzolana East Operations Hub',
    region: 'East India',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    address: 'Salt Lake Sector V, Block EP & GP, Kolkata, West Bengal 700091',
    phone: '+91 (33) 4008 7600',
    email: 'kolkata.zonal@puzzolana.com',
    contactPerson: 'Zonal Head - East',
    tier: 'Corporate Regional Hub',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Surface Miners', 'Feeder Breakers'],
    capabilities: ['Coal & Bauxite Processing Consultation', 'Eastern Dedicated Spares Yard', 'Major Component Overhauls'],
    operatingHours: 'Mon - Sat: 9:00 AM - 7:00 PM',
    sparesDepot: true,
    coordinates: { lat: 22.5804, lng: 88.4378 },
  },
  {
    id: 'PZD-BBS-01',
    name: 'Odisha Mining & Mineral Infrastructure Hub',
    companyName: 'Kalinga Heavy Equipment Dealership',
    region: 'East India',
    city: 'Bhubaneswar',
    state: 'Odisha',
    country: 'India',
    address: 'Mancheswar Industrial Estate, Sector A, Bhubaneswar, Odisha 751010',
    phone: '+91 (674) 258 1900',
    email: 'odisha.dealers@puzzolana.com',
    contactPerson: 'Mining Equipment Specialist',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Surface Miners', 'Heavy Screen Units'],
    capabilities: ['Iron Ore Washing & Hydrocyclone Audits', 'Heavy Feeder Breaker Servicing', 'High-Cr Manganese Liners'],
    operatingHours: 'Mon - Sat: 8:30 AM - 6:30 PM',
    sparesDepot: true,
    coordinates: { lat: 20.3168, lng: 85.8647 },
  },
  {
    id: 'PZD-RNC-01',
    name: 'Jharkhand Mineral Processing Centre',
    companyName: 'Chotanagpur Crushing & Mining Partners',
    region: 'East India',
    city: 'Ranchi',
    state: 'Jharkhand',
    country: 'India',
    address: 'Tupudana Industrial Area, Hatia, Ranchi, Jharkhand 834003',
    phone: '+91 (651) 229 4410',
    email: 'ranchi.support@puzzolana.com',
    contactPerson: 'Service Supervisor',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Surface Miners'],
    capabilities: ['Open-Cast Mining Plant Calibration', 'Track Mobile Undercarriage Servicing', 'Jaw Frame Weld Audits'],
    operatingHours: 'Mon - Sat: 8:30 AM - 6:00 PM',
    sparesDepot: true,
    coordinates: { lat: 23.2922, lng: 85.2975 },
  },

  // INTERNATIONAL / GLOBAL
  {
    id: 'PZD-DXB-01',
    name: 'Middle East & North Africa (MENA) Hub',
    companyName: 'Puzzolana International FZE',
    region: 'International / Global',
    city: 'Dubai',
    state: 'Dubai Emirate',
    country: 'United Arab Emirates',
    address: 'Jebel Ali Free Zone (JAFZA), South Zone 1, PO Box 263412, Dubai, UAE',
    phone: '+971 (4) 880 9944',
    email: 'mena.sales@puzzolana.com',
    contactPerson: 'Managing Director - Middle East & Africa',
    tier: 'Corporate Regional Hub',
    authorizedLines: ['Stationary Crushing Plants (up to 1200 TPH)', 'Track Mobile Units', 'Sand Washing & VSI', 'Asphalt Pavers'],
    capabilities: ['Gulf Standard High-Ambient Cooling Audits', 'MENA Central Wear Spares Depot', 'Direct Sea Freight Dispatch'],
    operatingHours: 'Mon - Sat: 8:00 AM - 6:00 PM (GST)',
    sparesDepot: true,
    coordinates: { lat: 24.9984, lng: 55.0768 },
  },
  {
    id: 'PZD-NBO-01',
    name: 'East Africa Infrastructure & Quarry Hub',
    companyName: 'Puzzolana Africa Heavy Machinery Ltd',
    region: 'International / Global',
    city: 'Nairobi',
    state: 'Nairobi County',
    country: 'Kenya',
    address: 'Mombasa Road, Industrial Area, Near ICD, Nairobi, Kenya',
    phone: '+254 (20) 698 5000',
    email: 'eastafrica@puzzolana.com',
    contactPerson: 'Regional Director - East Africa',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Sand Washing Systems'],
    capabilities: ['East African Quarry Commissioning', 'Regional Manganese Spares Yard', 'Factory Certified Technicians'],
    operatingHours: 'Mon - Fri: 8:00 AM - 5:30 PM, Sat: 8:30 AM - 1:00 PM (EAT)',
    sparesDepot: true,
    coordinates: { lat: -1.3197, lng: 36.8523 },
  },
  {
    id: 'PZD-LSK-01',
    name: 'Central & Southern Africa Mining Depot',
    companyName: 'Puzzolana Mining Solutions Zambia Ltd',
    region: 'International / Global',
    city: 'Lusaka / Kitwe',
    state: 'Copperbelt',
    country: 'Zambia',
    address: 'Heavy Industrial Area, Kitwe / Head Office: Great East Road, Lusaka, Zambia',
    phone: '+260 (211) 293 800',
    email: 'zambia.mining@puzzolana.com',
    contactPerson: 'Copperbelt Operations Head',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Surface Miners', 'Track Mobile Units'],
    capabilities: ['Copper & Cobalt Ore Crushing Support', 'Extreme Duty Cone Mantles', 'Heavy Vibrating Screen Cloths'],
    operatingHours: 'Mon - Fri: 8:00 AM - 5:00 PM (CAT)',
    sparesDepot: true,
    coordinates: { lat: -12.8024, lng: 28.2132 },
  },
  {
    id: 'PZD-JKT-01',
    name: 'Southeast Asia Distribution & Support',
    companyName: 'PT Puzzolana Nusantara Machinery',
    region: 'International / Global',
    city: 'Jakarta',
    state: 'DKI Jakarta',
    country: 'Indonesia',
    address: 'Kawasan Industri Pulogadung, Jl. Rawa Gelam, Jakarta Timur 13930, Indonesia',
    phone: '+62 (21) 4682 9900',
    email: 'sea.sales@puzzolana.com',
    contactPerson: 'Southeast Asia Operations Lead',
    tier: 'Authorized 3S Dealership',
    authorizedLines: ['Stationary Crushing Plants', 'Track Mobile Units', 'Sand Washing Systems'],
    capabilities: ['Nickel & Andesite Crushing Flowsheets', 'SE Asia Spares Distribution', 'Field Service Crew'],
    operatingHours: 'Mon - Fri: 8:30 AM - 5:30 PM (WIB)',
    sparesDepot: true,
    coordinates: { lat: -6.1950, lng: 106.9150 },
  },
];

export const DEALER_BENEFITS: DealerBenefit[] = [
  {
    title: 'Puzzolana In-House Foundry Spares Allocation',
    description: 'Guaranteed OEM parts margins and direct allocation from Puzzolana’s 40,000 MT/year casting foundries with preferential lead times.',
    icon: 'Factory',
    stat: '40,000 MT',
  },
  {
    title: 'Hyderabad Engineering Academy Training',
    description: 'Complimentary full-spectrum factory certification in Hyderabad for your service technicians and application engineers.',
    icon: 'GraduationCap',
    stat: '100% Certified',
  },
  {
    title: 'Exclusive Territory Protection & Lead Sharing',
    description: 'Demarcated geographic territory protection with direct forwarding of online RFQs and quarry plant inquiries received from your jurisdiction.',
    icon: 'ShieldCheck',
    stat: 'Territory Lock',
  },
  {
    title: 'Turnkey Flowsheet & CAD Design Support',
    description: 'Direct collaboration with Puzzolana’s 120+ design engineers to generate customized 3D plant layouts and crush simulation models for clients.',
    icon: 'Layers',
    stat: '120+ Engineers',
  },
];
